### ISSUE TITLE
iterate home page design

### ISSUE THREAD

**Issue by ateich** [Mountain-Colt/fullstack#44]

**Comment by LiamSchauerman** [comment]
I really like using the cloud image. A couple ideas, take them or leave them: use a brighter image that looks less like a storm and/or use a picture where we are sitting above the clouds (bad example: http://ak.picdn.net/shutterstock/videos/1860406/preview/stock-footage-scenic-flight-above-the-clouds-towards-the-sun.jpg)

**Comment by LiamSchauerman** [comment]
^ i take this back i like the picture :D
